[directory]
truncation_symbol = "…/"

[jobs]
symbol = "+"

[java]
symbol = " "
style = "bold yellow"

[python]
symbol = " " 

[rust]
symbol = " "

[custom.cpp]
format = "via [$symbol($output )]($style)"
extensions = ["C", "cc", "cpp", "CPP", "c++", "cp", "cxx"]
symbol = " "
style = "blue bold"
disabled = false
