#!/usr/bin/env bash

mkcd() {
	mkdir -p "$1" && cd "$1"
}

help() {
	local var && var=$( command -v "$1" )
	local args && args=${*:2}
	
	if [[ ${var} = "alias "* ]]; then
		if [[ ${var} = *"'"* ]]; then
			var="${var%'*}"
			var="${var#*'}"
			var="${var} --help"
			eval "${var}" | bat -l man -p
		elif [[ ${var} = *"="* ]]; then
			var="${var##*=}"
			"${var}" "${args}" --help | bat -l man -p
		fi
	else
		"$@" --help | bat -l man -p
	fi
}

weather() {
	local location
	[[ -z $1 ]] && location="varanasi" || location="$1"
	curl wttr.in/"${location}"\?F
}
