#!/usr/bin/env bash

mkcd() {
	mkdir -p "$1" && cd "$1"
}

help() {
	"$@" --help | bat -l man -p
}

weather() {
	local location
	[[ -z $1 ]] && location="varanasi" || location="$1"
	curl wttr.in/"${location}"\?F
}
