add_newline = false

[line_break]
disabled = true

[directory]
truncation_symbol = "…/"

[jobs]
symbol = "+"

[java]
symbol = " "
style = "bold yellow"

[python]
symbol = " " 

[rust]
symbol = " "

[golang]
symbol = " "

[custom.cpp]
format = "via [$symbol($output )]($style)"
extensions = ["C", "cc", "cpp", "CPP", "c++", "cp", "cxx"]
symbol = "C++ "
style = "blue bold"
disabled = false

[custom.header]
format = "via [$symbol($output )]($style)"
extensions = ["h", "hpp"]
symbol = "H\\[PP\\] "
style = "yellow"
disabled = false

[custom.vim]
command = "vim --version | head -1 | cut -d\" \" -f5"
format = "via [$symbol v($output )]($style)"
files = [".vimrc"]
extensions = ["vim"]
symbol = ""
style = "green"
disabled = false

[custom.windows]
format = "via [$symbol($output )]($style)"
extensions = ["exe", "msi", "msc", "dll"]
symbol = "  "
style = "cyan"
disabled = false
